<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Edge effects on species establishement, growth and survival in an experimental plant invasion</title>

<script src="analysis_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="analysis_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="analysis_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="analysis_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="analysis_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="analysis_files/navigation-1.1/tabsets.js"></script>
<link href="analysis_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="analysis_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Edge effects on species establishement, growth and survival in an experimental plant invasion</h1>
<h4 class="date"><em>22 March, 2018</em></h4>

</div>

<div id="TOC">
<ul>
<li><a href="#experiment-a-seed-germination">Experiment A: Seed germination</a></li>
<li><a href="#experiment-b-seedling-survival-and-growth">Experiment B: Seedling survival and growth</a></li>
<li><a href="#site-data">Site data</a><ul>
<li><a href="#trees">Trees</a></li>
<li><a href="#light-availability">Light availability</a></li>
<li><a href="#soil-moisture">Soil moisture</a></li>
<li><a href="#litter">Litter</a></li>
</ul></li>
<li><a href="#species-data">Species data</a><ul>
<li><a href="#experiment-1-seed-germination">Experiment 1: Seed germination</a></li>
<li><a href="#experiment-2-seedling-growth-and-survival">Experiment 2: Seedling growth and survival</a><ul>
<li><a href="#seedling-survival">Seedling survival</a></li>
<li><a href="#seedling-height">Seedling height</a></li>
<li><a href="#seedling-diameter">Seedling diameter</a></li>
<li><a href="#seedling-biomass">Seedling biomass</a></li>
<li><a href="#seedling-relative-growth-rate-height">Seedling relative growth rate (height)</a></li>
<li><a href="#seedling-herbivory">Seedling herbivory</a></li>
</ul></li>
</ul></li>
<li><a href="#modeling">Modeling</a><ul>
<li><a href="#speciesdistancesite-level-grouping">Species/distance/site level grouping</a></li>
<li><a href="#biomass-model">Biomass model</a><ul>
<li><a href="#diagnostic-plots">Diagnostic plots</a></li>
<li><a href="#model-coefficients">Model coefficients</a></li>
</ul></li>
<li><a href="#diameter-model">Diameter model</a></li>
<li><a href="#relative-growth-rate-model">Relative growth rate model</a></li>
<li><a href="#growth-performance-results">Growth performance results</a></li>
<li><a href="#percent-germination-model">Percent germination model</a></li>
<li><a href="#seedling-survival-model">Seedling survival model</a></li>
<li><a href="#germination-and-survival-results">Germination and survival results</a></li>
<li><a href="#site-level-effects">Site-level effects</a></li>
<li><a href="#herbivory-model">Herbivory model</a></li>
</ul></li>
</ul>
</div>

<hr />
<pre><code>## # A tibble: 6 x 3
## # Groups: common_name [6]
##   common_name  `Mature forest` `Young forest`
## * &lt;fctr&gt;                 &lt;dbl&gt;          &lt;dbl&gt;
## 1 Autumn olive           1.36            2.34
## 2 Honeysuckle            0.770           2.03
## 3 Privet                 0.855           1.90
## 4 Dogwood                0.664           1.27
## 5 Redbud                 0.753           1.88
## 6 Spicebush              0.508           1.22</code></pre>
<table>
<thead>
<tr class="header">
<th style="text-align: left;">Species</th>
<th style="text-align: left;">Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dogwood (<em>Cornus florida</em>)</td>
<td style="text-align: left;">Native</td>
</tr>
<tr class="even">
<td style="text-align: left;">Redbud (<em>Cercis canadensis</em>)</td>
<td style="text-align: left;">Native</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spicebush (<em>Lindera benzoin</em>)</td>
<td style="text-align: left;">Native</td>
</tr>
<tr class="even">
<td style="text-align: left;">Autumn olive (<em>Elaeagnus umbellata</em>)</td>
<td style="text-align: left;">Non-native</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Honeysuckle (<em>Lonicera maackii</em>)</td>
<td style="text-align: left;">Non-native</td>
</tr>
<tr class="even">
<td style="text-align: left;">Privet (<em>Ligustrum obtusifolium</em>)</td>
<td style="text-align: left;">Non-native</td>
</tr>
</tbody>
</table>
<hr />
<section id="experiment-a-seed-germination" class="level1">
<h1>Experiment A: Seed germination</h1>
<ul>
<li>Ten seeds from each of six species (3 invaders, 3 natives) were placed at each distance at each site.</li>
</ul>
<hr />
</section>
<section id="experiment-b-seedling-survival-and-growth" class="level1">
<h1>Experiment B: Seedling survival and growth</h1>
<ul>
<li><p>Seedlings of six species (3 invaders, 3 natives) were planted at 12 forest sites classified as mature (&gt;60 years) or young (&lt;40 years).</p></li>
<li><p>Four seedlings of each species at distances of 0, 5, 10, 20, 40, and 60 meters from the roadway edge.</p></li>
<li><p>All seedlings were 10-15cm tall when planted</p></li>
</ul>
<hr />
<p><strong>H1:</strong> There is a negative effect on survival and growth for all species moving from edge to interior</p>
<ul>
<li>Performance will also be poorer in mature versus young forests</li>
</ul>
<p><strong>H2:</strong> Non-native species perform relatively better near the edge and in young forests.</p>
<ul>
<li>Native species perform relatively better in interior locations and in mature forests</li>
</ul>
<hr />
</section>
<section id="site-data" class="level1">
<h1>Site data</h1>
<p>We measured environmental and forest structure characteristics at each distance along each transect at each site.</p>
<section id="trees" class="level2">
<h2>Trees</h2>
<p>A 10-BAF wedge prism was used to quantify basal area. We identified and measured the DBH of the five nearest trees that were counted as “in” using the wedge prism.</p>
<p><img src="analysis_files/figure-html/trees-1.png" width="4200" /><img src="analysis_files/figure-html/trees-2.png" width="4200" /></p>
<p>Basal area essentially defines young (&lt;40 years) vs. mature forest (&gt;60 years), although the difference is much smaller at the edge (i.e. 0 m).</p>
</section>
<section id="light-availability" class="level2">
<h2>Light availability</h2>
<p>In the summer of 2005, photosynthetically active radiation (PAR) was measured as photosynthetic photon flux density (PPFD) at five locations at each distance at each site along a 5 m long transect parallel to the road. From these measurements, we calculated the percent available light at each location as the ratio of the PAR value to the PAR value measured in open sun.</p>
<p><img src="analysis_files/figure-html/light-1.png" width="4200" /><img src="analysis_files/figure-html/light-2.png" width="4200" /></p>
<p>Light availability decreases with distance to road with no overall difference between forest age, however, there is substantial variation within and between forest age depending on the specific distance. Averaged across forest age, light availability was greater at the forest edge (0 m) compared to other distances. At mature forest sites, light availability was greatest at the forest edge (0 m), but at young forest sites it was greatest at 20 m from the edge.</p>
<p>Basically this is a noisy and non-linear relationship. What I would generally expect is relatively high light availability at the edge, then a rapid decline to a steady-state as you move into the forest.</p>
</section>
<section id="soil-moisture" class="level2">
<h2>Soil moisture</h2>
<p>In the summer of 2005, we also collected 125 cm<sup>3</sup> mineral soil samples at the center of each 5 m transect to measure gravimetric water content.</p>
<p><img src="analysis_files/figure-html/soil-1.png" width="4200" /><img src="analysis_files/figure-html/soil-2.png" width="4200" /></p>
<p>Overall, soil moisture incarease further from the edge (p = .055), with a stronger relationship at young forest sites than mature forest sites (not significant except at 60 m). Still, the effective difference in the average soil moisture is only a couple percentage points.</p>
</section>
<section id="litter" class="level2">
<h2>Litter</h2>
<p>We collected leaf litter from within a 25 cm x 25 cm PVC frame at each of the six distances from roads at each site in December 2008</p>
<p><img src="analysis_files/figure-html/litter-1.png" width="4200" /><img src="analysis_files/figure-html/litter-2.png" width="4200" /></p>
<p>Litter is greater in mature forests than young forests, but decreases with distance from edge after 5 meters in mature forests and increases with distance from edge in young forests. Litter may be especially important for modeling germination.</p>
<hr />
</section>
</section>
<section id="species-data" class="level1">
<h1>Species data</h1>
<p>For all of these, the solid-fill symbols should be the non-native species.</p>
<section id="experiment-1-seed-germination" class="level2">
<h2>Experiment 1: Seed germination</h2>
<p><img src="analysis_files/figure-html/germination-1.png" width="4200" /><img src="analysis_files/figure-html/germination-2.png" width="4200" /><img src="analysis_files/figure-html/germination-3.png" width="4200" /></p>
<p>Although the relationship between germination and distance from edge was non-linaer, germination was greater overall for non-native than native species and tended to increase with distance for both groups in mature forests. In young forests, germination of native species had a small negative relationship with distance from edge. The greater germination success of non-native species was driven by autumnn olive, which had the highest average germination rate in each forest age (mature: 67.191358, young: 44.0744631).</p>
<table>
<caption>Average germination (%) of seeds for each species in each forest age.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Species</th>
<th style="text-align: left;">Status</th>
<th style="text-align: right;">Mature forest</th>
<th style="text-align: right;">Young forest</th>
<th style="text-align: right;">Average</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Autumn olive</td>
<td style="text-align: left;">Non-native</td>
<td style="text-align: right;">67.19</td>
<td style="text-align: right;">44.07</td>
<td style="text-align: right;">55.63</td>
</tr>
<tr class="even">
<td style="text-align: left;">Honeysuckle</td>
<td style="text-align: left;">Non-native</td>
<td style="text-align: right;">29.99</td>
<td style="text-align: right;">25.34</td>
<td style="text-align: right;">27.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Privet</td>
<td style="text-align: left;">Non-native</td>
<td style="text-align: right;">8.21</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">4.59</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dogwood</td>
<td style="text-align: left;">Native</td>
<td style="text-align: right;">23.85</td>
<td style="text-align: right;">12.34</td>
<td style="text-align: right;">18.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Redbud</td>
<td style="text-align: left;">Native</td>
<td style="text-align: right;">4.77</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">2.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spicebush</td>
<td style="text-align: left;">Native</td>
<td style="text-align: right;">2.18</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">6.09</td>
</tr>
</tbody>
</table>
</section>
<section id="experiment-2-seedling-growth-and-survival" class="level2">
<h2>Experiment 2: Seedling growth and survival</h2>
<section id="seedling-survival" class="level3">
<h3>Seedling survival</h3>
<pre><code>##  [1] &quot;site_name&quot;      &quot;site_code&quot;      &quot;age&quot;            &quot;distance&quot;      
##  [5] &quot;species&quot;        &quot;status&quot;         &quot;habitat_type&quot;   &quot;f_habitat&quot;     
##  [9] &quot;common_name&quot;    &quot;avg_basal_area&quot; &quot;avg_pct_light&quot;  &quot;litter_kg_m2&quot;  
## [13] &quot;pct_moisture&quot;   &quot;year&quot;           &quot;survival&quot;</code></pre>
<p><img src="analysis_files/figure-html/survival-1.png" width="4200" /><img src="analysis_files/figure-html/survival-2.png" width="4200" /><img src="analysis_files/figure-html/survival-3.png" width="4200" /></p>
<table>
<caption>Proportion of seedlings of each species surviving to 2006</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Species</th>
<th style="text-align: left;">Status</th>
<th style="text-align: right;">Mature forest</th>
<th style="text-align: right;">Young forest</th>
<th style="text-align: right;">Average</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Autumn olive</td>
<td style="text-align: left;">Non-native</td>
<td style="text-align: right;">48.53</td>
<td style="text-align: right;">50.69</td>
<td style="text-align: right;">49.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">Honeysuckle</td>
<td style="text-align: left;">Non-native</td>
<td style="text-align: right;">95.56</td>
<td style="text-align: right;">95.14</td>
<td style="text-align: right;">95.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Privet</td>
<td style="text-align: left;">Non-native</td>
<td style="text-align: right;">85.29</td>
<td style="text-align: right;">93.06</td>
<td style="text-align: right;">89.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dogwood</td>
<td style="text-align: left;">Native</td>
<td style="text-align: right;">61.03</td>
<td style="text-align: right;">41.67</td>
<td style="text-align: right;">51.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Redbud</td>
<td style="text-align: left;">Native</td>
<td style="text-align: right;">91.91</td>
<td style="text-align: right;">80.56</td>
<td style="text-align: right;">86.23</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spicebush</td>
<td style="text-align: left;">Native</td>
<td style="text-align: right;">86.76</td>
<td style="text-align: right;">88.19</td>
<td style="text-align: right;">87.48</td>
</tr>
</tbody>
</table>
<p>Seedling survival over the duration of the experiment was high across sites and species (NA). Autumn olive and dogwood had relatively low survival compared to the other species (AO: 49% mature, 50.7% young; DW: 60.4% mature, 41.7% young). Seedling survival for all other species averaged greater than 80%. In mature forests, autumn olive and dogwood both had lower survival with increasing distance from the edge, but in young forest autumn olive tended to have greater survival farther from the edge.</p>
<p>While these general linear trends with distance are present, the precise relationship with distance from edge is non-linear across all species. In mature forests, most species showed greatest survival at 5 and 10 m from the edge, with the exception of honeysuckle, which had greatest survival at distances of 20 m and greater. Honeysuckle also had the greatest proportion of overall surviving seedlings (94.8%). In contrast, seedling survival in young forests was overall lower for native than non-native species, and also lower at interior versus edge locations for native species, except for spicebush.</p>
</section>
<section id="seedling-height" class="level3">
<h3>Seedling height</h3>
<p><img src="analysis_files/figure-html/seedling_height-1.png" width="4200" /><img src="analysis_files/figure-html/seedling_height-2.png" width="4200" /><img src="analysis_files/figure-html/seedling_height-3.png" width="4200" /></p>
</section>
<section id="seedling-diameter" class="level3">
<h3>Seedling diameter</h3>
<p><img src="analysis_files/figure-html/seedling_diameter-1.png" width="4200" /><img src="analysis_files/figure-html/seedling_diameter-2.png" width="4200" /><img src="analysis_files/figure-html/seedling_diameter-3.png" width="4200" /></p>
</section>
<section id="seedling-biomass" class="level3">
<h3>Seedling biomass</h3>
<p><img src="analysis_files/figure-html/seedling_biomass-1.png" width="4200" /><img src="analysis_files/figure-html/seedling_biomass-2.png" width="4200" /><img src="analysis_files/figure-html/seedling_biomass-3.png" width="4200" /></p>
</section>
<section id="seedling-relative-growth-rate-height" class="level3">
<h3>Seedling relative growth rate (height)</h3>
<p><img src="analysis_files/figure-html/rel_growth-1.png" width="4200" /><img src="analysis_files/figure-html/rel_growth-2.png" width="4200" /><img src="analysis_files/figure-html/rel_growth-3.png" width="4200" /></p>
</section>
<section id="seedling-herbivory" class="level3">
<h3>Seedling herbivory</h3>
<pre><code>## # A tibble: 20,160 x 12
##    site… site… age   dist… spec… stat… habi… f_ha… comm… year  herb… surv…
##    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt; &lt;chr&gt; &lt;fct&gt; &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt;
##  1 Cica… CH    Youn…     0 R     Nati…     0 0-5 m Redb… 2004      1     1
##  2 Cica… CH    Youn…     0 R     Nati…     0 0-5 m Redb… 2004      1     1
##  3 Cica… CH    Youn…     0 R     Nati…     0 0-5 m Redb… 2004      1     1
##  4 Cica… CH    Youn…     0 R     Nati…     0 0-5 m Redb… 2004      1     1
##  5 Cica… CH    Youn…     0 D     Nati…     0 0-5 m Dogw… 2004      0     1
##  6 Cica… CH    Youn…     0 D     Nati…     0 0-5 m Dogw… 2004      0     1
##  7 Cica… CH    Youn…     0 D     Nati…     0 0-5 m Dogw… 2004      0     1
##  8 Cica… CH    Youn…     0 D     Nati…     0 0-5 m Dogw… 2004      0     1
##  9 Cica… CH    Youn…     0 R     Nati…     0 0-5 m Redb… 2004      2     1
## 10 Cica… CH    Youn…     0 R     Nati…     0 0-5 m Redb… 2004      2     1
## # ... with 20,150 more rows</code></pre>
<p><img src="analysis_files/figure-html/herbivory-1.png" width="4200" /><img src="analysis_files/figure-html/herbivory-2.png" width="4200" /><img src="analysis_files/figure-html/herbivory-3.png" width="4200" /></p>
<p>We’ve settled on doing a model to try and explain herbivory. First, I’m looking at whether there was any clear pattern in herbivory from year to year.</p>
<p><img src="analysis_files/figure-html/herbiv-by-year-1.png" width="4200" /></p>
<p>In young forests, herbivory increased with distance from edge for both native and non-native species, but decreased with distance from edge for native species in mature forests. There was no relationship between distance from edge and herbivory for non-native species in mature forests. Herbivory was greater on native than non-native species in both forest types.</p>
<p>Herbivory was categorized as leaf-loss, where 0 = no herbivory, 1 = ≤25%, 2 = 26-50%, 3 = 51-75%, 4 = 76-99%, and 5 = 100% leaf removal by herbivores.</p>
<p>What kind of herbivory might this be: Defoliators.</p>
<p>There’s not a particularly clear pattern in changes between years, just generally lower for the invasive species. I can still put year in as a factor to test it statistically. It looks like forest age will be important, and probably distance. Some species also appear to be more susceptible than others. I’m thinking a model along the lines of this to start:</p>
<p>herbivory ~ distance + age + year + pct_light + litter</p>
</section>
</section>
</section>
<section id="modeling" class="level1">
<h1>Modeling</h1>
<section id="speciesdistancesite-level-grouping" class="level2">
<h2>Species/distance/site level grouping</h2>
<p>This grouping of data would theoretically gives an average data point of the performance of each species at each distance at each site (n = 432). What we actually have is 420 observations, so we have 12 that were missing, I believe lost due to mowing at the edge. Upon investigating where observations were missing, we lost all seedlings at the 0 meter distance at the FR and HQ sites (n = 12), which means we have 10 instead of 12 observations for plants at 0 meters, but effectively equal observations of each species.</p>
<p>We calculated the average of biomass accumulated, diameter, and relative growth rate for height across the four replicates of each species at each distance at each site. These average values were used as the response variables in regression models.</p>
<p>response variable for each species as the average value at for that species at each distance and site, e.g.,</p>
<p>We calculated the average of each response variable</p>
<p>We fit linear mixed-effects regressions to model each performance response variable - biomass, final height, and relative growth rate of height. Following methods described in Zuur et al. (2009), we first parameterized a “beyond optimal” model with all possible explanatory variables and potential interactions and used this to find the optimal structure of the random effects component. After finding the optimal random structure we found the optimal fixed structure by removing statistically insignificant interactions and then main effects. The single weakest explanatory variable was removed and the model refit to identify the next weakest explantory variable. This process was repeated until only statistically significant variables remained and accepted this as the final optimal model. We checked the residual plots of the final models to assure there was no major violation of homogeneity in the residual variance. Biomass and diameter responses were natural logarithm-transformed to improve homogeneity of residual variance and normality of the data.</p>
<p>We used mixed-effects logistic regressions to model germination and survival probabilities for each species.</p>
<p>In all models we allowed the intercept to vary for species and site, and interpret the random intercepts of the performance metrics for each species. Models were fit and evaluated using the “lme4” (<span class="citation" data-cites="Bates2015">@Bates2015</span>) and “lmerTest” (<span class="citation" data-cites="Kuznetsova2017">@Kuznetsova2017</span>) packages in the R statistical computing environment. The coefficient estimates from rescaled continuous variables are reported in the figures. Percent light and percent moisture were centered to a mean of zero and divided by two standard deviations, and distance was rescaled to be between zero and one by dividing by the maximum distance value.</p>
<p>The factor f_age represents forest age, and a value of 1 indicates young forests while a value of 0 indicates mature forests.</p>
</section>
<section id="biomass-model" class="level2">
<h2>Biomass model</h2>
<section id="diagnostic-plots" class="level3">
<h3>Diagnostic plots</h3>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: 
## log(avg_biomass) ~ distance + avg_pct_light + f_age + avg_herbivory_04 +  
##     (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 828.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.1361 -0.5542 -0.0557  0.5871  3.2175 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.13764  0.3710  
##  common_name (Intercept) 0.04428  0.2104  
##  Residual                0.39638  0.6296  
## Number of obs: 399, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                    Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)       -0.551535   0.194547  18.200000  -2.835 0.010893 *  
## distance          -0.005048   0.001516 379.600000  -3.330 0.000954 ***
## avg_pct_light      0.013127   0.002319 389.100000   5.660 2.94e-08 ***
## f_age1             0.610356   0.223894   9.900000   2.726 0.021549 *  
## avg_herbivory_04  -0.074450   0.041274 372.600000  -1.804 0.072067 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc avg_p_ f_age1
## distance    -0.210                     
## avg_pct_lgh -0.249  0.110              
## f_age1      -0.560  0.007 -0.019       
## avg_hrbv_04 -0.222  0.004  0.025 -0.062</code></pre>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: 
## log(avg_biomass) ~ distance + avg_pct_light + f_age + avg_h_incidence_05 +  
##     (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 780.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.3922 -0.5452 -0.0282  0.5774  3.3355 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.14914  0.3862  
##  common_name (Intercept) 0.05772  0.2402  
##  Residual                0.38458  0.6201  
## Number of obs: 380, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                      Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)         -0.855374   0.217865  22.900000  -3.926  0.00068 ***
## distance            -0.004875   0.001535 360.700000  -3.176  0.00162 ** 
## avg_pct_light        0.013120   0.002329 369.800000   5.634  3.5e-08 ***
## f_age1               0.615474   0.232250   9.900000   2.650  0.02459 *  
## avg_h_incidence_05   0.300944   0.115000 365.300000   2.617  0.00924 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc avg_p_ f_age1
## distance    -0.201                     
## avg_pct_lgh -0.211  0.117              
## f_age1      -0.544  0.004 -0.021       
## avg_h_nc_05 -0.392  0.028 -0.023  0.040</code></pre>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: 
## log(avg_biomass) ~ distance + avg_pct_light + f_age + avg_h_incidence_06 +  
##     (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 764.9
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.3164 -0.5285 -0.0163  0.5972  3.1811 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.14792  0.3846  
##  common_name (Intercept) 0.06809  0.2609  
##  Residual                0.37975  0.6162  
## Number of obs: 374, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                      Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)         -0.817683   0.220857  22.300000  -3.702 0.001219 ** 
## distance            -0.005625   0.001553 354.900000  -3.623 0.000334 ***
## avg_pct_light        0.012715   0.002348 363.800000   5.415 1.11e-07 ***
## f_age1               0.593144   0.231220   9.800000   2.565 0.028549 *  
## avg_h_incidence_06   0.274227   0.115548 356.800000   2.373 0.018160 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc avg_p_ f_age1
## distance    -0.178                     
## avg_pct_lgh -0.198  0.131              
## f_age1      -0.524  0.007 -0.016       
## avg_h_nc_06 -0.379 -0.032 -0.057  0.008</code></pre>
<pre><code>## [1] 781.3155</code></pre>
<pre><code>##       R2m       R2c 
## 0.2132277 0.4984883</code></pre>
<pre><code>## [1] 841.6625</code></pre>
<pre><code>##       R2m       R2c 
## 0.2012321 0.4677353</code></pre>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: 
## log(avg_biomass) ~ distance + avg_pct_light + f_age + avg_h_incidence_06 +  
##     (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 764.9
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.3164 -0.5285 -0.0163  0.5972  3.1811 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.14792  0.3846  
##  common_name (Intercept) 0.06809  0.2609  
##  Residual                0.37975  0.6162  
## Number of obs: 374, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                      Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)         -0.817683   0.220857  22.300000  -3.702 0.001219 ** 
## distance            -0.005625   0.001553 354.900000  -3.623 0.000334 ***
## avg_pct_light        0.012715   0.002348 363.800000   5.415 1.11e-07 ***
## f_age1               0.593144   0.231220   9.800000   2.565 0.028549 *  
## avg_h_incidence_06   0.274227   0.115548 356.800000   2.373 0.018160 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc avg_p_ f_age1
## distance    -0.178                     
## avg_pct_lgh -0.198  0.131              
## f_age1      -0.524  0.007 -0.016       
## avg_h_nc_06 -0.379 -0.032 -0.057  0.008</code></pre>
<p><img src="analysis_files/figure-html/final-biomass-model-1.png" width="4200" /><img src="analysis_files/figure-html/final-biomass-model-2.png" width="4200" /><img src="analysis_files/figure-html/final-biomass-model-3.png" width="4200" /><img src="analysis_files/figure-html/final-biomass-model-4.png" width="4200" /></p>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: log(avg_biomass) ~ scaled_distance + scaled_pct_light + f_age +  
##     scaled_herbiv_incidence + (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 750.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.3164 -0.5285 -0.0163  0.5972  3.1811 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.14792  0.3846  
##  common_name (Intercept) 0.06809  0.2609  
##  Residual                0.37975  0.6162  
## Number of obs: 374, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                          Estimate Std. Error        df t value Pr(&gt;|t|)
## (Intercept)              -0.36735    0.19849  14.90000  -1.851 0.084170
## scaled_distance          -0.33753    0.09317 354.90000  -3.623 0.000334
## scaled_pct_light          0.38868    0.07178 363.80000   5.415 1.11e-07
## f_age1                    0.59314    0.23122   9.80000   2.565 0.028549
## scaled_herbiv_incidence   0.18216    0.07675 356.80000   2.373 0.018160
##                            
## (Intercept)             .  
## scaled_distance         ***
## scaled_pct_light        ***
## f_age1                  *  
## scaled_herbiv_incidence *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) scld_d scld_p_ f_age1
## scald_dstnc -0.182                      
## scld_pct_lg -0.015  0.131               
## f_age1      -0.584  0.007 -0.016        
## scld_hrbv_n -0.004 -0.032 -0.057   0.008</code></pre>
</section>
<section id="model-coefficients" class="level3">
<h3>Model coefficients</h3>
<p><img src="analysis_files/figure-html/biomass-ranef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/biomass-ranef-plot-2.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/biomass-fixef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/biomass-fixef-plot-2.png" width="4200" /></p>
<p>Conditional and marginal R<sup>2</sup> of the biomass model 0.2132277, 0.4984883</p>
<p>All species generated more aboveground biomass in young forests and at locations with greater light availability. Biomass production decreased with distance from the road/forest edge and (interestingly) with greater soil moisture, however, there was a significant interaction between distance and soil moisture indicating greater soil moisture at distances farther from the edge.</p>
<p>The random intercepts for each species show that native species generated less biomass than non-native species, with spicebush and dogwood performing particularly poorly. For the non-native species, privet and autumn olive were especially good at amassing biomass, with honeysuckle performing slightly less well.</p>
<p>Site-level biomass production was greater at CH, PR, LD, and SR, while lower at DG, FR, and GR. The intercepts for the other five sites all had confidence error estimates crossing zero, with absolute values of the intercepts &lt;0.12.</p>
<p>I’m exploring making plots of the marginal effects for each group in the random effects, particulalry for species, with special interest in the relationship with distance (edge effects). <img src="analysis_files/figure-html/sjPlot-biomass-1.png" width="4200" /></p>
<pre><code>## [[1]]</code></pre>
<p><img src="analysis_files/figure-html/sjPlot-biomass-2.png" width="4200" /></p>
<pre><code>## 
## [[2]]</code></pre>
<p><img src="analysis_files/figure-html/sjPlot-biomass-3.png" width="4200" /></p>
<pre><code>## 
## [[3]]</code></pre>
<p><img src="analysis_files/figure-html/sjPlot-biomass-4.png" width="4200" /></p>
<pre><code>## 
## [[4]]</code></pre>
<p><img src="analysis_files/figure-html/sjPlot-biomass-5.png" width="4200" /> <img src="analysis_files/figure-html/sjPlot-biomass-6.png" width="4200" /><img src="analysis_files/figure-html/sjPlot-biomass-7.png" width="4200" /><img src="analysis_files/figure-html/sjPlot-biomass-8.png" width="4200" /></p>
<p><del>What about fitting a separate models for each species? I don’t think this is necessary unless we want to be able to say something specific about the relationship between the response and specific predictors for each species. I think it is reasonable to assume that the plants generally respond similarly to things like soil moisture and light availability.</del></p>
</section>
</section>
<section id="diameter-model" class="level2">
<h2>Diameter model</h2>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: 
## log(avg_diameter) ~ distance + avg_pct_light + age + avg_h_incidence_06 +  
##     (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 73.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8816 -0.5938 -0.0050  0.5799  3.5611 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.013953 0.11812 
##  common_name (Intercept) 0.006426 0.08016 
##  Residual                0.059316 0.24355 
## Number of obs: 374, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                      Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)         8.099e-01  7.321e-02  2.680e+01  11.063 1.70e-11 ***
## distance           -1.411e-03  6.134e-04  3.556e+02  -2.300   0.0220 *  
## avg_pct_light       4.114e-03  9.219e-04  3.632e+02   4.462 1.08e-05 ***
## ageYoung forest     2.006e-01  7.280e-02  9.900e+00   2.756   0.0204 *  
## avg_h_incidence_06  9.376e-02  4.520e-02  3.395e+02   2.074   0.0388 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc avg_p_ agYngf
## distance    -0.212                     
## avg_pct_lgh -0.234  0.130              
## ageYongfrst -0.499  0.008 -0.020       
## avg_h_nc_06 -0.447 -0.032 -0.060  0.010</code></pre>
<p><img src="analysis_files/figure-html/final%20diameter%20model-1.png" width="4200" /><img src="analysis_files/figure-html/final%20diameter%20model-2.png" width="4200" /><img src="analysis_files/figure-html/final%20diameter%20model-3.png" width="4200" /><img src="analysis_files/figure-html/final%20diameter%20model-4.png" width="4200" /><img src="analysis_files/figure-html/final%20diameter%20model-5.png" width="4200" /></p>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: log(avg_diameter) ~ scaled_distance + scaled_pct_light + age +  
##     scaled_herbiv_incidence + (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 58.8
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8816 -0.5938 -0.0050  0.5799  3.5611 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.013953 0.11812 
##  common_name (Intercept) 0.006426 0.08016 
##  Residual                0.059316 0.24355 
## Number of obs: 374, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                          Estimate Std. Error        df t value Pr(&gt;|t|)
## (Intercept)               0.95930    0.06266  15.10000  15.309 1.30e-10
## scaled_distance          -0.08464    0.03681 355.60000  -2.300   0.0220
## scaled_pct_light          0.12575    0.02818 363.20000   4.462 1.08e-05
## ageYoung forest           0.20064    0.07280   9.90000   2.756   0.0204
## scaled_herbiv_incidence   0.06228    0.03003 339.50000   2.074   0.0388
##                            
## (Intercept)             ***
## scaled_distance         *  
## scaled_pct_light        ***
## ageYoung forest         *  
## scaled_herbiv_incidence *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) scld_d scld_p_ agYngf
## scald_dstnc -0.228                      
## scld_pct_lg -0.019  0.130               
## ageYongfrst -0.583  0.008 -0.020        
## scld_hrbv_n -0.005 -0.032 -0.060   0.010</code></pre>
<p><img src="analysis_files/figure-html/diameter-ranef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/diameter-ranef-plot-2.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/diameter-fixef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/diameter-fixef-plot-2.png" width="4200" /></p>
<p>Conditional and marginal R<sup>2</sup> estimated for the diameter model 0.1772482, 0.3876369</p>
<p>Seedling diameter increased with light availability and was greater in younger forests, but decreased with distance.</p>
<p><img src="analysis_files/figure-html/sjplot-diameter-1.png" width="4200" /><img src="analysis_files/figure-html/sjplot-diameter-2.png" width="4200" /><img src="analysis_files/figure-html/sjplot-diameter-3.png" width="4200" /></p>
</section>
<section id="relative-growth-rate-model" class="level2">
<h2>Relative growth rate model</h2>
<p>The units of relative growth rate are percent change per day (I think).</p>
<p>Do we actually want to test/know what the slope/intercept interaction is between distance and species as a rondom component??</p>
<pre><code>## Linear mixed model fit by REML t-tests use Satterthwaite approximations
##   to degrees of freedom [lmerMod]
## Formula: 
## log(avg_diameter) ~ distance + avg_pct_light + age + avg_h_incidence_06 +  
##     (1 | site_code) + (1 | common_name)
##    Data: site_grouped_data
## 
## REML criterion at convergence: 73.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8816 -0.5938 -0.0050  0.5799  3.5611 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.013953 0.11812 
##  common_name (Intercept) 0.006426 0.08016 
##  Residual                0.059316 0.24355 
## Number of obs: 374, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                      Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)         8.099e-01  7.321e-02  2.680e+01  11.063 1.70e-11 ***
## distance           -1.411e-03  6.134e-04  3.556e+02  -2.300   0.0220 *  
## avg_pct_light       4.114e-03  9.219e-04  3.632e+02   4.462 1.08e-05 ***
## ageYoung forest     2.006e-01  7.280e-02  9.900e+00   2.756   0.0204 *  
## avg_h_incidence_06  9.376e-02  4.520e-02  3.395e+02   2.074   0.0388 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc avg_p_ agYngf
## distance    -0.212                     
## avg_pct_lgh -0.234  0.130              
## ageYongfrst -0.499  0.008 -0.020       
## avg_h_nc_06 -0.447 -0.032 -0.060  0.010</code></pre>
<p><img src="analysis_files/figure-html/final%20rgr%20model-1.png" width="4200" /><img src="analysis_files/figure-html/final%20rgr%20model-2.png" width="4200" /><img src="analysis_files/figure-html/final%20rgr%20model-3.png" width="4200" /><img src="analysis_files/figure-html/final%20rgr%20model-4.png" width="4200" /><img src="analysis_files/figure-html/final%20rgr%20model-5.png" width="4200" /></p>
<pre><code>##              (Intercept)     distance avg_pct_light ageYoung forest
## Autumn olive   0.8341711 -0.001410739   0.004113719       0.2006376
## Honeysuckle    0.8577471 -0.001410739   0.004113719       0.2006376
## Privet         0.9002381 -0.001410739   0.004113719       0.2006376
## Dogwood        0.7319488 -0.001410739   0.004113719       0.2006376
## Redbud         0.8264401 -0.001410739   0.004113719       0.2006376
## Spicebush      0.7086994 -0.001410739   0.004113719       0.2006376
##              avg_h_incidence_06
## Autumn olive         0.09376174
## Honeysuckle          0.09376174
## Privet               0.09376174
## Dogwood              0.09376174
## Redbud               0.09376174
## Spicebush            0.09376174</code></pre>
<p><img src="analysis_files/figure-html/rgr-ranef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/rgr-ranef-plot-2.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/rgr-fixef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/rgr-fixef-plot-2.png" width="4200" /></p>
<p>Conditional and marginal R<sup>2</sup> estimated for the diameter model 0.1772482, 0.3876369</p>
<p>The nonnative species autumn olive had the best performance in terms of relative growth rate (height), followed by privet. The native redbud and, and nonnative honeysuckle, had similar baseline performance in relative growth rate. Spicebush had the lowest relative growth rate. The effects of the explanatory variables on relative growth rate were all in the same directions as for diameter and biomass.</p>
<p><img src="analysis_files/figure-html/sjplot-rgr-1.png" width="4200" /><img src="analysis_files/figure-html/sjplot-rgr-2.png" width="4200" /><img src="analysis_files/figure-html/sjplot-rgr-3.png" width="4200" /><img src="analysis_files/figure-html/sjplot-rgr-4.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/gridded-dot-line-plots-1.png" width="4200" /></p>
</section>
<section id="growth-performance-results" class="level2">
<h2>Growth performance results</h2>
<p>Seedling growth metrics of biomass, diameter, and relative growth rate of height all responded similarly to edge effects, moisture and light availability, and forest successional age. Growth increased with light availability and was greater in young forests and decreased with distance from edge and moisture availability. The nonnative species generally performed better than the native species, however, there was species specific variability among growth metrics. The nonnative species privet, autumn olive, and honeysuckle had the best performance in terms of above-ground biomass relative to the overall average, while the native dogwood and spicebush generated relatively small amounts of biomass. The average biomass produced by the native redbud was close to the overall average across all the species. Privet also showed the greatest increase in diameter relative to the other species, while dogwood and especially spicebush had relatively small increases in diameter. Autumn olive and privet had the two highest relative growth rates in height and spicebush had the lowest. Relative growth rates of redbud, dogwood, and honeysuckle were similar, and near the overall average across all species.</p>
</section>
<section id="percent-germination-model" class="level2">
<h2>Percent germination model</h2>
<p>Logistic regression with number of trials (seeds germinated:seeds recovered)</p>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: 
## cbind(seeds_germinated, seeds_present) ~ distance + age + litter_kg_m2 +  
##     (1 | site_code) + (1 | common_name)
##    Data: germination_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    820.0    844.3   -404.0    808.0      425 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.7113 -0.6165 -0.2536  0.2654  4.9852 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.08699  0.2949  
##  common_name (Intercept) 1.26869  1.1264  
## Number of obs: 431, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -2.540634   0.552877  -4.595 4.32e-06 ***
## distance         0.004564   0.002311   1.974   0.0483 *  
## ageYoung forest -0.393468   0.215068  -1.830   0.0673 .  
## litter_kg_m2     0.350322   0.200727   1.745   0.0809 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc agYngf
## distance    -0.145              
## ageYongfrst -0.277  0.004       
## littr_kg_m2 -0.467  0.082  0.253</code></pre>
<p><img src="analysis_files/figure-html/final%20germination%20model-1.png" width="4200" /><img src="analysis_files/figure-html/final%20germination%20model-2.png" width="4200" /><img src="analysis_files/figure-html/final%20germination%20model-3.png" width="4200" /><img src="analysis_files/figure-html/final%20germination%20model-4.png" width="4200" /><img src="analysis_files/figure-html/final%20germination%20model-5.png" width="4200" /></p>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: cbind(seeds_germinated, seeds_present) ~ scaled_distance + age +  
##     scaled_litter_kg_m2 + (1 | site_code) + (1 | common_name)
##    Data: germination_data
## 
##      AIC      BIC   logLik deviance df.resid 
##    820.0    844.3   -404.0    808.0      425 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.7113 -0.6165 -0.2536  0.2654  4.9852 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.08699  0.2949  
##  common_name (Intercept) 1.26870  1.1264  
## Number of obs: 431, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)          -2.1671     0.4909  -4.415 1.01e-05 ***
## scaled_distance       0.2738     0.1387   1.974   0.0483 *  
## ageYoung forest      -0.3935     0.2151  -1.830   0.0673 .  
## scaled_litter_kg_m2   0.2266     0.1298   1.745   0.0809 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) scld_d agYngf
## scald_dstnc -0.127              
## ageYongfrst -0.201  0.004       
## scld_ltt__2 -0.090  0.082  0.253</code></pre>
<p><img src="analysis_files/figure-html/germ-ranef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/germ-ranef-plot-2.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/germ-fixef-plot-1.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/sjplot-germination-1.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-2.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-3.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-4.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-5.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-6.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-7.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-8.png" width="4200" /><img src="analysis_files/figure-html/sjplot-germination-9.png" width="4200" /></p>
</section>
<section id="seedling-survival-model" class="level2">
<h2>Seedling survival model</h2>
<p>Logistic regression to estimate species-level survival probabilities.</p>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: 
## cbind(alive, dead) ~ distance + age + litter_kg_m2 + (1 | site_code) +  
##     (1 | common_name) + (1 | obs_id)
##    Data: survival_2006
## 
##      AIC      BIC   logLik deviance df.resid 
##    922.1    950.3   -454.0    908.1      412 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.7498 -0.2994  0.2914  0.4587  1.1419 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  obs_id      (Intercept) 2.088    1.445   
##  site_code   (Intercept) 1.018    1.009   
##  common_name (Intercept) 2.400    1.549   
## Number of obs: 419, groups:  obs_id, 419; site_code, 12; common_name, 6
## 
## Fixed effects:
##                  Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)      2.106874   0.937527   2.247   0.0246 *
## distance        -0.004210   0.005035  -0.836   0.4031  
## ageYoung forest -0.225238   0.632839  -0.356   0.7219  
## litter_kg_m2     0.223423   0.422281   0.529   0.5967  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc agYngf
## distance    -0.136              
## ageYongfrst -0.437  0.011       
## littr_kg_m2 -0.549  0.008  0.196</code></pre>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: 
## cbind(alive, dead) ~ scaled_distance + age + scaled_litter_kg_m2 +  
##     (1 | site_code) + (1 | common_name)
##    Data: survival_2006
## 
##      AIC      BIC   logLik deviance df.resid 
##    998.8   1023.1   -493.4    986.8      413 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -7.0152 -0.7619  0.3999  0.7006  3.0638 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.6959   0.8342  
##  common_name (Intercept) 1.5121   1.2297  
## Number of obs: 419, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                     Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)          1.78596    0.62285   2.867  0.00414 **
## scaled_distance     -0.20750    0.19026  -1.091  0.27543   
## ageYoung forest     -0.15033    0.50744  -0.296  0.76704   
## scaled_litter_kg_m2  0.05921    0.08691   0.681  0.49567   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) scld_d agYngf
## scald_dstnc -0.126              
## ageYongfrst -0.411  0.010       
## scld_ltt__2 -0.062  0.001  0.156</code></pre>
<p><img src="analysis_files/figure-html/final%20survival%20model-1.png" width="4200" /><img src="analysis_files/figure-html/final%20survival%20model-2.png" width="4200" /><img src="analysis_files/figure-html/final%20survival%20model-3.png" width="4200" /><img src="analysis_files/figure-html/final%20survival%20model-4.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/surv-ranef-plot-1.png" width="4200" /><img src="analysis_files/figure-html/surv-ranef-plot-2.png" width="4200" /></p>
<p><img src="analysis_files/figure-html/surv-fixef-plot-1.png" width="4200" /></p>
<p>The estimated marginal and condiational R<sup>2</sup> values reinforce that the fixed effects don’t explain the variance in seedling survival:</p>
<p>0.0037321, 0.3908736</p>
<p><img src="analysis_files/figure-html/survival-sjplot-1.png" width="4200" /><img src="analysis_files/figure-html/survival-sjplot-2.png" width="4200" /><img src="analysis_files/figure-html/survival-sjplot-3.png" width="4200" /><img src="analysis_files/figure-html/survival-sjplot-4.png" width="4200" /><img src="analysis_files/figure-html/survival-sjplot-5.png" width="4200" /><img src="analysis_files/figure-html/survival-sjplot-6.png" width="4200" /><img src="analysis_files/figure-html/survival-sjplot-7.png" width="4200" /></p>
</section>
<section id="germination-and-survival-results" class="level2">
<h2>Germination and survival results</h2>
<p>The probability of germination increased with distance from edge, light availability, litter mass, and basal area, but the effect of basal area was moderated by forest successional age, with lower germination in young forests. Effects of measured site conditions on survival were relatively weak and predominantly due to interaction variables. Light availability had a significant positive effect on survival probability, but this decreased with distance from the edge (indicated by the negative interaction term). The positive interaction of distance and litter increased survival probability, although the main effects of distance and litter were statistically insignificant. The interaction of basal area and forest age was similar, but with a negative effect where seedlings at locations with lower basal area in younger forests had lower probability of survival. Variation in survival depended predominantly on species specific characteristics and unmeasured site characteristics as indicated by the variance accounted for by these random effects variables.</p>
<p>Germination probability for the nonnative autumn olive and honeysuckle, and native dogwood was greater than the overall average; privet, redbud, and spicebush had below average germination, with spicebush being the lowest. In contrast, the transplanted autumn olive and dogwood seedlings had the lowest survival probability, while honeysuckle, privet, spicebush, and redbud seedlings all showed above average survival. Honeysuckle seedlings were particularly likely to persist to the end of the experiment.</p>
</section>
<section id="site-level-effects" class="level2">
<h2>Site-level effects</h2>
<p>Growth was relativley poor for all the metrics at the DG, FR, and GR, and tended to be greatest at the CH and PR sites. In addition to the CH and PR sites, seedlings at the LD and SR sites tended to perform well in terms of biomass; seedling diameters at the TC and SR sites were also greater than average, but lagged well-behind the CH site; relative-growth-rate tended to be greater than average at the BB and LD, but the PR site was the best for this variable. In terms of survival, the CH site was the most favorable, while seedling survival was similar and above average at the TC, DU, and PR sites. Probability of germination was close to the average across most of the site, but exceptionally greater at the DB site, and exceptionally lower at the DU site.</p>
<p><img src="analysis_files/figure-html/gridded-site-ranef-fig-1.png" width="4200" /></p>
</section>
<section id="herbivory-model" class="level2">
<h2>Herbivory model</h2>
<p>General model formulation: herbivory ~ distance + age + year + pct_light + litter</p>
<p>I’m not actually sure how to fit a model to these data. It’s ordinal in that the categories indicate the range of herbivory in terms of leaf area affected. Herbivory was categorized as leaf-loss, where</p>
<ul>
<li>0 = no herbivory</li>
<li>1 = ≤25%</li>
<li>2 = 26-50%</li>
<li>3 = 51-75%</li>
<li>4 = 76-99%</li>
<li>5 = 100% leaf removal by herbivores</li>
</ul>
<p>The internet has some suggestions on how to do this for mixed-effects models: <a href="https://stats.stackexchange.com/questions/238581/how-to-use-ordinal-logistic-regression-with-random-effects?noredirect=1&amp;lq=1"></a></p>
<p>The <code>ordinal</code> package has the <code>clmm</code> and <code>clmm2</code>, with will probably suffice for my purposes. I just need to get a decent inference off the data. Two other packages implement Bayesian MCMC frameworsks: <a href="https://cran.r-project.org/package=MCMCglmm">MCMCglmm</a> and <a href="https://cran.r-project.org/package=brms">brms</a>.</p>
<p>Other studies have looked at incidence, i.e., presence/absence of herbivory at each observation, so we could take that approach.</p>
<pre><code>##   site_name          site_code             age               distance    
##  Length:5040        Length:5040        Length:5040        Min.   : 0.00  
##  Class :character   Class :character   Class :character   1st Qu.: 5.00  
##  Mode  :character   Mode  :character   Mode  :character   Median :20.00  
##                                                           Mean   :23.14  
##                                                           3rd Qu.:40.00  
##                                                           Max.   :60.00  
##                                                                          
##    species                 status      habitat_type     f_habitat   
##  Length:5040        Native    :2520   Min.   :0.000   0-5 m  :1584  
##  Class :character   Non-native:2520   1st Qu.:0.000   10-20 m:1728  
##  Mode  :character                     Median :1.000   40-60 m:1728  
##                                       Mean   :1.029                 
##                                       3rd Qu.:2.000                 
##                                       Max.   :2.000                 
##                                                                     
##        common_name      year             herbivory    
##  Autumn olive:840   Length:5040        Min.   :0.000  
##  Honeysuckle :840   Class :character   1st Qu.:0.000  
##  Privet      :840   Mode  :character   Median :1.000  
##  Dogwood     :840                      Mean   :1.088  
##  Redbud      :840                      3rd Qu.:1.000  
##  Spicebush   :840                      Max.   :5.000  
##                                        NA&#39;s   :978</code></pre>
<pre><code>##   site_name          site_code             age               distance    
##  Length:4062        Length:4062        Length:4062        Min.   : 0.00  
##  Class :character   Class :character   Class :character   1st Qu.: 5.00  
##  Mode  :character   Mode  :character   Mode  :character   Median :20.00  
##                                                           Mean   :22.71  
##                                                           3rd Qu.:40.00  
##                                                           Max.   :60.00  
##    species                 status      habitat_type     f_habitat   
##  Length:4062        Native    :1964   Min.   :0.000   0-5 m  :1290  
##  Class :character   Non-native:2098   1st Qu.:0.000   10-20 m:1417  
##  Mode  :character                     Median :1.000   40-60 m:1355  
##                                       Mean   :1.016                 
##                                       3rd Qu.:2.000                 
##                                       Max.   :2.000                 
##        common_name      year             herbivory     herbivory_incidence
##  Autumn olive:521   Length:4062        Min.   :0.000   Min.   :0.000      
##  Honeysuckle :806   Class :character   1st Qu.:0.000   1st Qu.:0.000      
##  Privet      :771   Mode  :character   Median :1.000   Median :1.000      
##  Dogwood     :494                      Mean   :1.088   Mean   :0.707      
##  Redbud      :720                      3rd Qu.:1.000   3rd Qu.:1.000      
##  Spicebush   :750                      Max.   :5.000   Max.   :1.000</code></pre>
<p><img src="analysis_files/figure-html/ordinal-vs-incidence-1.png" width="4200" /><img src="analysis_files/figure-html/ordinal-vs-incidence-2.png" width="4200" /></p>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: 
## f_herbiv_incidence ~ distance + age * year + status + (1 | site_code) +  
##     (1 | common_name)
##    Data: herbiv_noNA_data
## 
##      AIC      BIC   logLik deviance df.resid 
##   4473.0   4536.1  -2226.5   4453.0     4052 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -5.3723 -0.9920  0.4119  0.6865  1.3240 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.07192  0.2682  
##  common_name (Intercept) 0.32008  0.5658  
## Number of obs: 4062, groups:  site_code, 12; common_name, 6
## 
## Fixed effects:
##                            Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)               1.3843435  0.3606555   3.838 0.000124 ***
## distance                 -0.0008086  0.0017456  -0.463 0.643194    
## ageYoung forest           0.4028182  0.1946030   2.070 0.038457 *  
## year2005                  0.5708527  0.1262667   4.521 6.15e-06 ***
## year2006                  0.5440517  0.1281367   4.246 2.18e-05 ***
## statusNon-native         -1.2069354  0.4695301  -2.571 0.010155 *  
## ageYoung forest:year2005 -0.9267511  0.1747619  -5.303 1.14e-07 ***
## ageYoung forest:year2006 -0.4315990  0.1802183  -2.395 0.016626 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) distnc agYngf yr2005 yr2006 sttsN- aYf:2005
## distance    -0.111                                            
## ageYongfrst -0.264  0.011                                     
## year2005    -0.142  0.001  0.272                              
## year2006    -0.140 -0.003  0.269  0.418                       
## statsNn-ntv -0.657 -0.004 -0.004 -0.004 -0.003                
## agYfrs:2005  0.101 -0.001 -0.407 -0.721 -0.300  0.005         
## agYfrs:2006  0.101  0.005 -0.393 -0.294 -0.707  0.000  0.440</code></pre>
<pre><code>## [1] 4472.969</code></pre>
<pre><code>## Cumulative Link Mixed Model fitted with the Laplace approximation
## 
## formula: f_herbiv ~ distance + age * year + status + (1 | site_code) +  
##     (1 | common_name)
## data:    herbiv_noNA_data
## 
##  link  threshold nobs logLik   AIC     niter      max.grad cond.H 
##  logit flexible  4062 -4879.14 9786.28 1113(3340) 1.06e-02 3.3e+05
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  site_code   (Intercept) 0.05269  0.2296  
##  common_name (Intercept) 0.28432  0.5332  
## Number of groups:  site_code 12,  common_name 6 
## 
## Coefficients:
##                            Estimate Std. Error z value Pr(&gt;|z|)    
## distance                 -0.0001806  0.0014249  -0.127 0.899139    
## ageYoung forest           0.4289984  0.1658279   2.587 0.009681 ** 
## year2005                  0.3427562  0.1015191   3.376 0.000735 ***
## year2006                  0.3998139  0.1027399   3.892 9.96e-05 ***
## statusNon-native         -1.3415312  0.4401605  -3.048 0.002305 ** 
## ageYoung forest:year2005 -0.6863718  0.1439552  -4.768 1.86e-06 ***
## ageYoung forest:year2006 -0.3468326  0.1448112  -2.395 0.016617 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##     Estimate Std. Error z value
## 0|1  -1.5302     0.3340  -4.582
## 1|2   0.8605     0.3332   2.582
## 2|3   2.1538     0.3355   6.419
## 3|4   3.4150     0.3438   9.934
## 4|5   4.0871     0.3544  11.532</code></pre>
</section>
</section>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
